# -*- coding: utf-8 -*-
"""PRODIGY_DS_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7FNo9lbLljVLzU7xHN8TR9KzUrO7CWB
"""



import matplotlib.pyplot as plt

# Sample data
genders = ['Male', 'Female']
counts = [40, 60]  # number of males and females in the population

# Create a bar chart
plt.bar(genders, counts)
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Distribution of Genders')
plt.show()

"""**Histogram Example: Distribution of Ages**

Now, let's say we have a continuous variable age and we want to visualize its distribution in the population.
"""

import matplotlib.pyplot as plt
import numpy as np

# Sample data
ages = np.random.normal(30, 10, 100)  # generate 100 random ages with mean 30 and std dev 10

# Create a histogram
plt.hist(ages, bins=10, edgecolor='black')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Distribution of Ages')
plt.show()

"""Now using a dataset"""